### ISSUE TITLE
Leaderboard: 429 errors when querying addresses

### ISSUE THREAD

**Issue by biwasbhandari** [aibtcdev/aibtcdev-frontend#76]
It works fine on my local machine, but on the deployed version, I am getting a 429 error. Although I've implemented caching on the frontend, I think we should move balance fetching to the backend (FastAPI) and create an endpoint to view all balances, managing the cache there as well.

Any other ideas will be helpful.

**Comment by whoabuddy** [comment]
For one, we can double check the Hiro API key is set correctly in the deployment. I'll take a look when I kick off the next one in Replit.

Were you thinking we can use a combination of the back-end and the database? Maybe we use the contestant table and add some columns?

Big picture we need a place to store:
- all user STX balances
- all user FT balances (array of items, varies per user)

Then for each we'll need a price from somewhere, maybe CMC or CoinGecko, unless we can pull from an on-chain source:
- current STX price
- current FT price for each FT listed

We can also implement some rate limiting and/or back-off to the updater so that if it runs into hiccups it'll just retry a few times at a slower pace. It should also be designed as a "self-healing" process, so if it fails next step is just to run it again (manual or on a timer).

In the future we may want to break this out into it's own micro-service. The patterns here are something a lot of Stacks apps deal with!

What do you think we need to get started?

**Comment by Rapha-btc** [comment]
I'm curious where we're going to get prices from for FTs. I ran into this a few weeks back, asked the Leo / Stackspulse teams fwiw.

**Comment by biwasbhandari** [comment]
> For one, we can double check the Hiro API key is set correctly in the deployment. I'll take a look when I kick off the next one in Replit.
> 
> Were you thinking we can use a combination of the back-end and the database? Maybe we use the contestant table and add some columns?
> 
> Big picture we need a place to store:
> - all user STX balances
> - all user FT balances (array of items, varies per user)
> 
> Then for each we'll need a price from somewhere, maybe CMC or CoinGecko, unless we can pull from an on-chain source:
> - current STX price
> - current FT price for each FT listed
> 
> We can also implement some rate limiting and/or back-off to the updater so that if it runs into hiccups it'll just retry a few times at a slower pace. It should also be designed as a "self-healing" process, so if it fails next step is just to run it again (manual or on a timer).
> 
> In the future we may want to break this out into it's own micro-service. The patterns here are something a lot of Stacks apps deal with!
> 
> What do you think we need to get started?

I think it's better if we do it in the backend. We can just get a list of all the participants and send the req and manage the api request for hiro api. Since we have lots of tools in the backend it might be easier and less load on the frontend too.

**Comment by whoabuddy** [comment]
> I'm curious where we're going to get prices from for FTs. I ran into this a few weeks back, asked the Leo / Stackspulse teams fwiw.

Would be awesome if Leo / stxtools.io price feeds were accessible. Would love to pull in their API data for agents in a few ways!

**Comment by whoabuddy** [comment]
> I think it's better if we do it in the backend. We can just get a list of all the participants and send the req and manage the api request for hiro api. Since we have lots of tools in the backend it might be easier and less load on the frontend too.

I've got an idea for this using Cloudflare and some caching magic, but if that doesn't pan out then we can create something in the backend.
